//
//  WeatherPresenter.swift
//  Super Weather
//
//  Created by Игорь Силаев on 11.08.2020.
//  Copyright (c) 2020 Игорь Силаев. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WeatherPresenterInput {
    
}

protocol WeatherPresenterOutput: class {
    
}

class WeatherPresenter: WeatherPresenterInput {
    
    weak var output: WeatherPresenterOutput?
    
    // MARK: Presentation logic
    
}
