//
//  WeatherConfigurator.swift
//  Super Weather
//
//  Created by Игорь Силаев on 11.08.2020.
//  Copyright (c) 2020 Игорь Силаев. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension WeatherInteractor: WeatherViewControllerOutput, WeatherRouterDataSource, WeatherRouterDataDestination {
}

extension WeatherPresenter: WeatherInteractorOutput {
}

final class WeatherConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = WeatherConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: WeatherViewController) {
        
        let presenter = WeatherPresenter()
        presenter.output = viewController
        
        let interactor = WeatherInteractor()
        interactor.output = presenter
        
        let router = WeatherRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
