//
//  WeatherInteractor.swift
//  Super Weather
//
//  Created by Игорь Силаев on 11.08.2020.
//  Copyright (c) 2020 Игорь Силаев. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WeatherInteractorInput {
    
}

protocol WeatherInteractorOutput {
    
}

protocol WeatherDataSource {
    
}

protocol WeatherDataDestination {
    
}

class WeatherInteractor: WeatherInteractorInput, WeatherDataSource, WeatherDataDestination {
    
    var output: WeatherInteractorOutput?
    
    // MARK: Business logic
    

}
